# Preparing Data For RAG
In this notebook, we will standardize the .csv files, concatenate them into one final dataframe, and save that dataframe.

## Setup

In [1]:
# importing libraries
import os
import pandas as pd
import numpy as np
import ast

In [2]:
# defining data paths
ROOT_PATH = "./data"
CSV_PATHS = [os.path.join(ROOT_PATH, path) for path in os.listdir(ROOT_PATH) if path.endswith(".csv")]
print(CSV_PATHS)

['./data\\jobs_1_data.csv', './data\\jobs_3_data.csv', './data\\jobs_4_data.csv', './data\\jobs_5_data.csv']

---
---

## Standardizing Datasets

**First Dataset**

In [3]:
CSV_PATHS[0]

'./data\\jobs_1_data.csv'

In [4]:
df1 = pd.read_csv(CSV_PATHS[0])
df1.head()

,title,description,year
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,2025
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,2025
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",2025
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",2025
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",2025

**Second Dataset**

In [5]:
CSV_PATHS[1]

'./data\\jobs_3_data.csv'

In [6]:
df2 = pd.read_csv(CSV_PATHS[1])
df2.head()

,job_title,job_description,tags,year,description_lengths
0,development and implementation of a federated ...,please bid only if you are ready to do the wor...,"['algorithm', 'java', 'python', 'machine learn...",2024,189
1,Data Entry -- 2,Project Title: Data Entry - Data Analysis in E...,"['excel', 'statistical analysis', 'statistics'...",2024,151
2,Build API access to data,Project Title: Build API access to acquired fl...,"['python', 'php', 'javascript', 'software arch...",2024,177
3,Develop an AI website from the ground up,I am looking for a skilled developer to create...,"['java', 'website design', 'html', 'python', '...",2024,136
4,"Develop a Linux based BT receiving daemon to ""...",I am looking for a skilled freelancer to devel...,"['linux', 'python', 'c programming', 'shell sc...",2024,223

In [7]:
df2 = df2.copy().drop(columns = ['description_lengths'])
df2.head()

,job_title,job_description,tags,year
0,development and implementation of a federated ...,please bid only if you are ready to do the wor...,"['algorithm', 'java', 'python', 'machine learn...",2024
1,Data Entry -- 2,Project Title: Data Entry - Data Analysis in E...,"['excel', 'statistical analysis', 'statistics'...",2024
2,Build API access to data,Project Title: Build API access to acquired fl...,"['python', 'php', 'javascript', 'software arch...",2024
3,Develop an AI website from the ground up,I am looking for a skilled developer to create...,"['java', 'website design', 'html', 'python', '...",2024
4,"Develop a Linux based BT receiving daemon to ""...",I am looking for a skilled freelancer to devel...,"['linux', 'python', 'c programming', 'shell sc...",2024

In [8]:
rename_dict = {
    'job_title' : 'title',
    'job_description' : 'description',
    'tags' : 'skills'
}

df2 = df2.copy().rename(columns = rename_dict)
df2.head()

,title,description,skills,year
0,development and implementation of a federated ...,please bid only if you are ready to do the wor...,"['algorithm', 'java', 'python', 'machine learn...",2024
1,Data Entry -- 2,Project Title: Data Entry - Data Analysis in E...,"['excel', 'statistical analysis', 'statistics'...",2024
2,Build API access to data,Project Title: Build API access to acquired fl...,"['python', 'php', 'javascript', 'software arch...",2024
3,Develop an AI website from the ground up,I am looking for a skilled developer to create...,"['java', 'website design', 'html', 'python', '...",2024
4,"Develop a Linux based BT receiving daemon to ""...",I am looking for a skilled freelancer to devel...,"['linux', 'python', 'c programming', 'shell sc...",2024

In [9]:
df2.skills.iloc[0]

"['algorithm', 'java', 'python', 'machine learning (ml)', 'flutter']"

In [10]:
ast.literal_eval(df2.skills.iloc[0])

['algorithm', 'java', 'python', 'machine learning (ml)', 'flutter']

In [11]:
df2['skills'] = df2['skills'].apply(ast.literal_eval)
df2.head()

,title,description,skills,year
0,development and implementation of a federated ...,please bid only if you are ready to do the wor...,"[algorithm, java, python, machine learning (ml...",2024
1,Data Entry -- 2,Project Title: Data Entry - Data Analysis in E...,"[excel, statistical analysis, statistics, spss...",2024
2,Build API access to data,Project Title: Build API access to acquired fl...,"[python, php, javascript, software architectur...",2024
3,Develop an AI website from the ground up,I am looking for a skilled developer to create...,"[java, website design, html, python, php]",2024
4,"Develop a Linux based BT receiving daemon to ""...",I am looking for a skilled freelancer to devel...,"[linux, python, c programming, shell script, s...",2024

**Third Dataset**

In [12]:
CSV_PATHS[2]

'./data\\jobs_4_data.csv'

In [13]:
df3 = pd.read_csv(CSV_PATHS[2])
df3.head()

,Position,description,Refined_Category
0,1926/07 Senior Java Software Engineer,**Your responsibilities**\r\n- Take ownership ...,Software & Web Development
1,1st / 2nd Line IT Support Engineer,THE ROLE:\r\nOur Engineers help small business...,Administrative & Data Entry
2,2037/03 Middle/Senior Python Developer,"**A stable long term project, growing customer...",Software & Web Development
3,2037/03 Middle/Senior Python Developer,Looking for an experienced Python engineer who...,Software & Web Development
4,24/7 Junior DevOps,**Qualifications and experience:**\r\n- Interm...,DevOps & Infrastructure

In [14]:
rename_dict = {
    'Position' : 'title',
    'Refined_Category' : 'category'
}

df3 = df3.copy().rename(columns = rename_dict)
df3.head()

,title,description,category
0,1926/07 Senior Java Software Engineer,**Your responsibilities**\r\n- Take ownership ...,Software & Web Development
1,1st / 2nd Line IT Support Engineer,THE ROLE:\r\nOur Engineers help small business...,Administrative & Data Entry
2,2037/03 Middle/Senior Python Developer,"**A stable long term project, growing customer...",Software & Web Development
3,2037/03 Middle/Senior Python Developer,Looking for an experienced Python engineer who...,Software & Web Development
4,24/7 Junior DevOps,**Qualifications and experience:**\r\n- Interm...,DevOps & Infrastructure

In [15]:
# !!!
df3['year'] = 2023

df3.head()

,title,description,category,year
0,1926/07 Senior Java Software Engineer,**Your responsibilities**\r\n- Take ownership ...,Software & Web Development,2023
1,1st / 2nd Line IT Support Engineer,THE ROLE:\r\nOur Engineers help small business...,Administrative & Data Entry,2023
2,2037/03 Middle/Senior Python Developer,"**A stable long term project, growing customer...",Software & Web Development,2023
3,2037/03 Middle/Senior Python Developer,Looking for an experienced Python engineer who...,Software & Web Development,2023
4,24/7 Junior DevOps,**Qualifications and experience:**\r\n- Interm...,DevOps & Infrastructure,2023

**Fourth Dataset**

In [16]:
CSV_PATHS[3]

'./data\\jobs_5_data.csv'

In [17]:
df4 = pd.read_csv(CSV_PATHS[3])
df4.head()

,Job Title,Description,best_category
0,"File Maker Pro Reports, Charts, Query and Ongo...",NITIAL PROJECT\r\n\r\nSet up Monthly Report mi...,Data Analyst
1,BI and Data Engineer for Upwork Finance System...,The Upwork Finance Systems team is looking for...,Data Analyst
2,Computer vision / machine learning: synthetic ...,Our company is working on a government proposa...,Video Producer
3,Expert in Data Analytics,Mission : Ensure smooth transition of Analytic...,Data Analyst
4,Data Analytics Expert for Educational Exercise,Looking for someone to help me solve some prob...,Data Analyst

In [18]:
rename_dict = {
    'Job Title' : 'title',
    'Description' : 'description',
    'best_category' : 'category'
}

df4 = df4.copy().rename(columns = rename_dict)
df4.head()

,title,description,category
0,"File Maker Pro Reports, Charts, Query and Ongo...",NITIAL PROJECT\r\n\r\nSet up Monthly Report mi...,Data Analyst
1,BI and Data Engineer for Upwork Finance System...,The Upwork Finance Systems team is looking for...,Data Analyst
2,Computer vision / machine learning: synthetic ...,Our company is working on a government proposa...,Video Producer
3,Expert in Data Analytics,Mission : Ensure smooth transition of Analytic...,Data Analyst
4,Data Analytics Expert for Educational Exercise,Looking for someone to help me solve some prob...,Data Analyst

In [19]:
df4['year'] = 2023

df4.head()

,title,description,category,year
0,"File Maker Pro Reports, Charts, Query and Ongo...",NITIAL PROJECT\r\n\r\nSet up Monthly Report mi...,Data Analyst,2023
1,BI and Data Engineer for Upwork Finance System...,The Upwork Finance Systems team is looking for...,Data Analyst,2023
2,Computer vision / machine learning: synthetic ...,Our company is working on a government proposa...,Video Producer,2023
3,Expert in Data Analytics,Mission : Ensure smooth transition of Analytic...,Data Analyst,2023
4,Data Analytics Expert for Educational Exercise,Looking for someone to help me solve some prob...,Data Analyst,2023

**Text Files**

In [20]:
TXT_ROOT_PATH = 'data/jobs_2_data/'
position_paths = [os.path.join(TXT_ROOT_PATH, position) for position in os.listdir(TXT_ROOT_PATH)]

print(position_paths)

['data/jobs_2_data/AI Engineer', 'data/jobs_2_data/Backend Developer', 'data/jobs_2_data/Content Writer', 'data/jobs_2_data/Data Analyst', 'data/jobs_2_data/DevOps Engineer', 'data/jobs_2_data/Frontend Developer', 'data/jobs_2_data/Graphic Designer', 'data/jobs_2_data/Mobile Developer', 'data/jobs_2_data/Video Producer']

In [21]:
def load_txt_file(path):
    with open(path, 'r') as f:
        content = f.read()
    return content

In [22]:
import re
def extract_data(job: str):
    job = job.split(']')[1].strip()
    lines = job.split("\n\n")
    return {
        'title' : lines[0].split(":")[1].strip(),
        'responsibilities' : lines[1].split(":")[1].strip().split(", "),
        'tech_skills' : lines[2].split(":")[1].strip().split(", "),
        'tools' : lines[3].split(":")[1].strip().split(", "),
        'soft_skills' : lines[4].split(":")[1].strip().split(", "),
    }

In [23]:
def format_data(data: dict) -> str:
    """
    Turns the data dictionary into a formal job description.
    """    
    def to_bullets(items):
        cleaned_items = []
        for item in items:
            # Remove "and " if it's at the start of the string
            clean_item = item.strip()
            if clean_item.lower().startswith("and "):
                clean_item = clean_item[4:]
            
            # Capitalize the first letter and add bullet
            cleaned_items.append(f"• {clean_item.capitalize()}")
        
        return "\n".join(cleaned_items)

    job_desc = f"""
Key Responsibilities
{to_bullets(data.get('responsibilities', []))}

Technical Skills
{to_bullets(data.get('tech_skills', []))}

Soft Skills
{to_bullets(data.get('soft_skills', []))}

Tools & Software
{to_bullets(data.get('tools', []))}
"""
    return job_desc

In [24]:
# reading the .txt jobs into csv
txt_data = []
for pos_idx, pos_folder in enumerate(position_paths, start = 1):
    position = pos_folder.split("/")[-1]
    print(f'>> Position #_{pos_idx} - {position}')

    # all files in that position folder
    n_error_files = 0
    for file_idx, file in enumerate(os.listdir(pos_folder)):
        try:
            print(end = "\t")
            print(f'Finished {file_idx} files')
            
            # skip `Fundamental skills & Recent Trends`
            if "Job" not in file:
                continue
            
            # read file
            file_path = os.path.join(pos_folder, file)
            file_content = load_txt_file(file_path)
            data = extract_data(file_content)
    
            # extract data
            title = data['title']
            description = format_data(data)
            year = 2026
    
            # save
            txt_data.append({
                'title' : title,
                'description' : description,
                'year' : year
            })

        # skip errornos files
        except:
            n_error_files += 1
            pass

    print(f"Number of Files with Errors: {n_error_files}")

    print()
    print()

>> Position #_1 - AI Engineer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_2 - Backend Developer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_3 - Content Writer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_4 - Data Analyst
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 1


>> Position #_5 - DevOps Engineer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_6 - Frontend Developer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_7 - Graphic Designer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_8 - Mobile Developer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0


>> Position #_9 - Video Producer
	Finished 0 files
	Finished 1 files
	Finished 2 files
	Finished 3 files
	Finished 4 files
	Finished 5 files
	Finished 6 files
	Finished 7 files
	Finished 8 files
	Finished 9 files
	Finished 10 files
	Finished 11 files
Number of Files with Errors: 0

In [25]:
txt_to_df = pd.DataFrame(txt_data)
txt_to_df.head()

,title,description,year
0,Senior AI Engineer (Production-grade systems).,\nKey Responsibilities\n• Designing rag pipeli...,2026
1,Machine Learning Developer (Sports Betting Str...,\nKey Responsibilities\n• Creating predictive ...,2026
2,Senior Data Scientist / Applied AI Engineer (E...,\nKey Responsibilities\n• Designing multi-moda...,2026
3,ML/NLP Engineer (Foundational & Strategy Focus).,\nKey Responsibilities\n• Designing scalable d...,2026
4,Computer Vision Engineer (Padel Sports Analyti...,\nKey Responsibilities\n• Improving player tra...,2026

---
---

## Concatenating Datasets

In [26]:
df_final = pd.concat(
    objs = [df1, df2, df3, df4, txt_to_df],
    axis = 0
)

In [27]:
df_final.head(n = 10)

,title,description,year,skills,category
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,2025,NaN,NaN
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,2025,NaN,NaN
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",2025,NaN,NaN
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",2025,NaN,NaN
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",2025,NaN,NaN
5,"Staff Data Scientist, Research, Search Platforms",Note: By applying to this position you will ha...,2025,NaN,NaN
6,"Applied AI/ML, Senior Associate - Gen AI & LLM",JOB DESCRIPTION\n\nLeverage your technical exp...,2025,NaN,NaN
7,"Executive Director, ML and Ad Marketplace","Universal Ads, a part of Comcast, enables any ...",2025,NaN,NaN
8,AI/ML Engineer,Riverside Overview: Riverside Research is an i...,2025,NaN,NaN
9,Senior Software Engineer - AI/ML,Why Mayo Clinic\n\nMayo Clinic is top-ranked i...,2025,NaN,NaN

In [28]:
df_final.tail(n = 10)

,title,description,year,skills,category
79,Video Production Specialist (Multi-Platform Co...,\nKey Responsibilities\n• Conceptualizing and ...,2026,NaN,NaN
80,SaaS Video Producer (Software Demo & Feature S...,\nKey Responsibilities\n• Writing concise\n• B...,2026,NaN,NaN
81,Videographer & Location Scout (Corporate/Talk-...,\nKey Responsibilities\n• Scouting and securin...,2026,NaN,NaN
82,Short-Form Ad Creator (eCommerce & Performance...,\nKey Responsibilities\n• Developing simple ad...,2026,NaN,NaN
83,Whiteboard Animator / Explainer Video Specialist.,\nKey Responsibilities\n• Executing a 2\n\nTec...,2026,NaN,NaN
84,Video Producer (Non-Profit & Event Presentatio...,\nKey Responsibilities\n• Producing a long-for...,2026,NaN,NaN
85,Motion Graphics Designer & Product Video Speci...,\nKey Responsibilities\n• Translating existing...,2026,NaN,NaN
86,Motion Graphics Artist & Video Producer (SaaS ...,\nKey Responsibilities\n• Executing high-quali...,2026,NaN,NaN
87,Podcast & Video Production Specialist (Multi-P...,\nKey Responsibilities\n• Editing raw audio fo...,2026,NaN,NaN
88,Video Production Specialist (Scripting & Editi...,\nKey Responsibilities\n• Developing engaging ...,2026,NaN,NaN

In [29]:
df_final.shape

(36207, 5)

In [30]:
df_final.to_csv(path_or_buf = 'data/final_data.csv')

In [34]:
df_final.isna().sum()

title              0
description        0
year               0
skills         33163
category        3845
dtype: int64

---
---

## Chunking Data

**Exploring Lengths**

In [4]:
df_final = pd.read_csv('data/final_data.csv', index_col = 0)
df_final.head()

,title,description,year,skills,category
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,2025,NaN,NaN
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,2025,NaN,NaN
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",2025,NaN,NaN
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",2025,NaN,NaN
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",2025,NaN,NaN

In [5]:
df_final['description_lengths'] = df_final['description'].str.split().apply(len)
df_final.head()

,title,description,year,skills,category,description_lengths
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,2025,NaN,NaN,447
1,Senior AI Engineer - Data Scientist,This is where you save and sustain lives\n\nAt...,2025,NaN,NaN,1083
2,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",2025,NaN,NaN,573
3,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",2025,NaN,NaN,692
4,AI / Machine Learning Research Engineer (early...,"Job ID: 694362BR\nDate posted: May. 22, 2025\n...",2025,NaN,NaN,863

In [6]:
df_final['description_lengths'].describe()

count    36207.000000
mean       188.877040
std        142.275673
min          4.000000
25%        110.000000
50%        162.000000
75%        238.000000
max       2621.000000
Name: description_lengths, dtype: float64

**Remove Rows without Sufficient Info**

In [7]:
def print_job_descs(job_descs: list):
    for job_desc in job_descs:
        print(job_desc)
        print(100 * '-')

In [8]:
filt = df_final['description_lengths'] <= 30
df_final[filt].shape

(2114, 6)

In [9]:
small_job_descs = df_final[filt].sort_values(by = ['description_lengths'], ascending = False)['description'].values.tolist()

print_job_descs(small_job_descs[:5])

Work on social media content including video and visual assets. Producing and editing dynamic pieces of content for social distribution.

Looking to complete about 4 to 5 videos a month.
----------------------------------------------------------------------------------------------------
Hello,

We are searching for a personal branding consultant to develop content for a professional's personal LinkedIn. Goal is to increase thought leadership profile, reach and engagement with the content.
----------------------------------------------------------------------------------------------------
Website designer who can work with wordpress and work with design homepages we have, you can then edit the site and create other pages and make other wordpress updates needed.
----------------------------------------------------------------------------------------------------
HI,
I am looking for good iOS developer that can update few things in my app

Fix some wrong texts
fix some UI issue on iOS 15 and 16

thanks
----------------------------------------------------------------------------------------------------
We have a working prototype built and a designer for the UI. We're looking for an expert for a conversation on what's needed to finish it and implement those changes.
----------------------------------------------------------------------------------------------------

In [10]:
# removing rows with len(desc) <= 30 --> no enough info included
df_final = df_final[~filt]
df_final.shape

(34093, 6)

In [11]:
df_final.description_lengths.describe()

count    34093.000000
mean       199.381574
std        140.017670
min         31.000000
25%        118.000000
50%        170.000000
75%        245.000000
max       2621.000000
Name: description_lengths, dtype: float64

**Chunking Rows with Long Descriptions**

In [12]:
def get_fixed_size_chunks(text: str, chunk_size: int = 700, overlap: int = 100) -> list:
    words = text.split()
    chunks = []
    
    i = 0
    while i < len(words):
        end = i + chunk_size
        chunk = " ".join(words[i:end])
        chunks.append(chunk)
        
        i += (chunk_size - overlap)
        
        if i + overlap >= len(words):
            break
            
    return chunks

In [13]:
filt = df_final['description_lengths'] > 700
data_above_700 = df_final[filt].copy()
data_above_700.shape

(426, 6)

In [14]:
data_above_700.description_lengths.describe()

count     426.000000
mean      956.669014
std       273.197452
min       701.000000
25%       778.500000
50%       873.000000
75%      1057.500000
max      2621.000000
Name: description_lengths, dtype: float64

In [15]:
data_above_700['description'] = data_above_700['description'].apply(
    lambda x : get_fixed_size_chunks(text = x)
)

data_above_700_expanded = data_above_700.copy().explode('description', ignore_index = True)
data_above_700_expanded.shape

(897, 6)

In [16]:
data_below_700 = df_final[~filt]
data_below_700.shape

(33667, 6)

In [17]:
data_below_700.description_lengths.describe()

count    33667.000000
mean       189.799358
std        107.528035
min         31.000000
25%        117.000000
50%        168.000000
75%        241.000000
max        700.000000
Name: description_lengths, dtype: float64

In [18]:
df_final_v2 = pd.concat(
    objs = [data_below_700, data_above_700_expanded],
    axis = 0,
    ignore_index = True
).drop(columns = ['description_lengths'])

df_final_v2.shape

(34564, 5)

In [19]:
df_final_v2.head()

,title,description,year,skills,category
0,"Senior Data Scientist, Research, YouTube Search",Note: By applying to this position you will ha...,2025,NaN,NaN
1,"Audio Software Engineer, Applied Scientist","Redmond, WA • + 2 more•Full Time\nMessenger\nM...",2025,NaN,NaN
2,"Software Engineer, Machine Learning","Bellevue, WA • Full Time\nMeta\nSoftware Engin...",2025,NaN,NaN
3,"Staff Data Scientist, Research, Search Platforms",Note: By applying to this position you will ha...,2025,NaN,NaN
4,"Research Engineer, Speech & Language - Generat...","Bellevue, WA • + 2 more•Full Time\nMeta\nAI Re...",2025,NaN,NaN

In [20]:
df_final_v2['description_lengths'] = df_final_v2['description'].str.split().apply(len)
df_final_v2.description_lengths.describe()

count    34564.000000
mean       198.027312
std        123.130245
min         31.000000
25%        118.000000
50%        170.000000
75%        247.000000
max        700.000000
Name: description_lengths, dtype: float64

In [21]:
df_final_v2.to_csv("data/final_data.csv")

---
---

***Alhamdulillah***